services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '80:80'
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node prisma/seed.js && rm -rf ./data && npm run start:prod"
    restart: unless-stopped
    networks:
      - my-network
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
